### ISSUE TITLE
Add Stories to Backlog

### ISSUE THREAD

**Issue by littleorangeplanet** [NYU-Shopcarts/shopcarts#13]
**As a** Product Owner
**I need** to create a backlog of stories
**So that** the team knows what to do in Sprint 1

**Assumptions:** 
* I have the backlog of stories, so I will know the goal of Sprint 1.

**Acceptance Criteria:**
```
Given I have a backlog of stories
When I proceed to Sprint 1
Then I will know what needs to be done in this stage
```

**Comment by pranaypareek** [comment]
Moving this back to In Progress since we added new stories and haven't groomed them yet.

**Comment by pranaypareek** [comment]
All stories were groomed and moved to backlog or icebox so closing this issue.
