### ISSUE TITLE
Create the design for all CRUD routes

### ISSUE THREAD

**Issue by pranaypareek** [NYU-Shopcarts/shopcarts#15]
**As a** developler
**I need** to know the what to name the API routes
**So that** I can create a standardized API

**Assumptions:** 
* We can create and publish a documentation for the Shopcarts API

**Acceptance Criteria:**
```
Given that I'm a user of the Shopcarts API
When my client calls the CRUD routes on the Shopcarts API
Then my products gets created, updated, deleted, or fetched from the Shopcarts DB
```

**Comment by alicelisisi** [comment]
hey, pranay, did u see the file that professor has , maybe we should just modify his file, then it will be consistent with our model file and other test files.

**Comment by pranaypareek** [comment]
Hi @alicelisisi, I think that makes sense, that will certainly make it easy to write the test cases as well. I'll follow this.

**Comment by alicelisisi** [comment]
@pranaypareek  great! let us know how it goes or you need help, kedar and i already modified model.py file and model's test, once we have the server.py, we will be able to test all of them! i hope you are feeling better.
