### ISSUE TITLE
Create the schema for Shopcarts DB object

### ISSUE THREAD

**Issue by pranaypareek** [NYU-Shopcarts/shopcarts#16]
**As a** developer
**I need** to have a schema for the Shopcarts database object
**So that** I can use that schema to support my API routes

**Assumptions:** 
* We will use MongoDB and follow the standards on how MongoDB schemas are designed

**Acceptance Criteria:**
```
Given that the schema for a Shopcarts object exists
When I call the GET, POST, PUT API routes
Then the corresponding changes succeed on the actual DB object
```

**Comment by kqg13** [comment]
Schema for object discussed today:
1) ID: Integer
2) Name: String(len=80)
3) Count: Integer
4) Price: Float/Double
5) Link: String
6) isAvailable: Boolean
7) BrandName: String(len=80)
