### ISSUE TITLE
update all API routes to include "/shopcarts" keyword

### ISSUE THREAD

**Issue by alicelisisi** [NYU-Shopcarts/shopcarts#34]
**As a** developer
**I need**  ```/shopcarts``` also in the API routes
**So that** we are more explicit about what our service is

**Assumptions:** 
* Resources are accessible using `GET /shopcarts/item/id` and other CRUD functionalities

**Acceptance Criteria:**
```
Given that resources exist in the db
When we access resources on /shopcarts/items
Then they should be returned
```

**Comment by pranaypareek** [comment]
Updated the comment with criteria, assumptions etc

**Comment by pranaypareek** [comment]
All tests were good. Merged.
