### ISSUE TITLE
Part2: Add Persistence to application

### ISSUE THREAD

**Issue by alicelisisi** [NYU-Shopcarts/shopcarts#52]
**As a** developer
**I need** to connect Bluemix database to  our application
**So that**  we have persistence for the shopcart service  

**Assumptions:** 
* Mysql database was connected to shopcart service on Bluemix

**Acceptance Criteria:**
```
Given our model was bound through VCAP_SERVICES environment variable
When we run tests
Then they should pass
```

**Comment by kqg13** [comment]
Woking on conforming to MySql
