### ISSUE TITLE
Part 3: Create BDD Test for Shopping Cart Features

### ISSUE THREAD

**Issue by littleorangeplanet** [NYU-Shopcarts/shopcarts#68]
**As a Developer** ...  
**I need to run the BDD test for shopping carts** ...  
**So that I can assure the application functions** ...  

**Assumptions:** 
* All the functions and features are established and ready for BDD testing.

**Acceptance Criteria:**
```
Given the functions and features are ready for test
When BDD test completes
Then all the features, scenarios, and steps should be passed
```

**Comment by pranaypareek** [comment]
This issue is no longer needed.
