### ISSUE TITLE
Part 3: Create a BDD .feature file and accompanying .steps file for RESTful API

### ISSUE THREAD

**Issue by littleorangeplanet** [NYU-Shopcarts/shopcarts#70]
**As a** Developer
**I need** a list of features to be tested and the scenarios implementing the tests (at least 7 Scenarios: one for each of Create, Read, Update, Delete, List, Query, and Action) ...  
**So that** I need to create a BDD .feature file and an accompanying .steps file to test the RESTful API ...  

**Assumptions:** 
* All the functions and features are in place

**Acceptance Criteria:**
```All the features and scenarios are passed
Given the behaviors that we have promised to our stakeholders
When we perform the behaviors on the list
Then the expected results should be matched with the .feature file
```

**Comment by pranaypareek** [comment]
This is done and verified.
