### ISSUE TITLE
Part 3: Create a UI for Shopcarts API

### ISSUE THREAD

**Issue by littleorangeplanet** [NYU-Shopcarts/shopcarts#71]
**As a** customer
**I need** a UI
**So that** I can directly interact with the application and utilize all the functions

**Assumptions:** 
* The Shopcarts API functions and features are all in place

**Acceptance Criteria:**
```
Given Shopcarts API
When we interact with a UI
Then we can add or delete products into or from the shop cart, and preview the goods in the shop cart.
```

**Comment by pranaypareek** [comment]
UI is up on Bluemix.
