### ISSUE TITLE
Create an App skeleton

### ISSUE THREAD

**Issue by littleorangeplanet** [NYU-Shopcarts/shopcarts#8]
**As a** developer
**I need** to create a skeletal app
**So that** I can start working on the project

**Assumptions:** 
* The app has the required framework/dependencies set up and a very basic server runs

**Acceptance Criteria:**
```
Given that I've cloned the repository
When I run the app
Then the web server should start up
```

**Comment by pranaypareek** [comment]
In the first iteration which makes up the skeletal app, I'm putting in placeholders for:

```
GET /
GET /shopcarts/items
GET /shopcarts/items/:item_id:
POST /shopcarts/items
```
Please note that these do not have a full functionality and we'll need to work on these in the specific issues for each route.

**Comment by pranaypareek** [comment]
PR merged, closing this.
